---
- name: Add elrepo key
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Install elrepo
  yum:
    name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
    state: present

- name: Install kernel
  yum:
    enablerepo: elrepo-kernel
    name: kernel-ml,kernel-ml-devel
    state: latest

- name: Remove old kernel tools
  yum:
    name: kernel-tools-libs.x86_64,kernel-tools.x86_64
    state: absent

- name: Install new kernel tools
  yum:
    enablerepo: elrepo-kernel
    name: kernel-ml-tools
    state: latest

#- name: Upgrade kernel
#  yum:
#    enablerepo: elrepo-kernel
#    name: '*'
#    state: latest

- name: Set latest kernel as default
  raw: grub2-set-default 0
